# Generated by Django 5.2.4 on 2025-09-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='event_banners/'),
            preserve_default=False,
        ),
    ]
